name: fhir_generator
description: A package serving for generating fhir specific dart classes
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  build: ^2.3.0
  freezed_annotation: ^1.1.0
  io: ^1.0.3
  json_annotation: ^4.5.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  lints: ^1.0.0
  test: ^1.21.0
